# .github/workflows/embedder.yml
name: Build & Push Embedding Worker Image

on:
  push:
    paths:
      - 'embedding_worker/**'
      - 'common/**'
      - '.github/workflows/embedder.yml'

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: embedding_worker/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository_owner }}/embedding-worker:latest
